# increment-patch-version.yml

# Copyright (c) Bitstro Systems. All rights reserved.
# Licensed under BSDL 1.0

name: Increment Patch Version
on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'src/bstk/**'
      - '!src/bstk/res/**'

  workflow_dispatch:
        
jobs:
  increment_patch_version:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Increment patch version
        shell: pwsh
        run: >
          ./tools/Increment-PatchVersion.ps1

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add ./tools/version
          git commit -m "(AUTO) Increment patch version"
          git push origin ${{ github.ref_name }}